<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Commands\General\Static\CopyFileFromRegToDisk.txt" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Commands\General\Static\CopyFileFromDiskToReg.txt" />
    <EmbeddedResource Include="Commands\General\Static\CopyFileFromRegToDisk.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Management.Infrastructure" Version="3.0.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
