<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resource\Deployment\VMWare\SetNicIdInRegistry.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.16.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="EzSmb" Version="1.3.10" />
    <PackageReference Include="Microsoft.Graph" Version="5.93.0" />
    <PackageReference Include="Microsoft.Graph.Beta" Version="5.111.0-preview" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="SMBLibrary" Version="1.5.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IRH.Lib.VMWare\IRH.Lib.VMWare.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resource\Deployment\VMWare\SetNicIdInRegistry.txt" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
