//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRH.Ui.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRH.Ui.Resources.Strings.de", typeof(Strings_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktion.
        /// </summary>
        public static string Azure_Action_Label {
            get {
                return ResourceManager.GetString("Azure_Action_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiere den Geräte Code welcher angezeigt wird in die Zwischenablage.
        /// </summary>
        public static string Azure_ActionBar_CopyDeviceCode_ToolTip {
            get {
                return ResourceManager.GetString("Azure_ActionBar_CopyDeviceCode_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffne die Microsoft Geräte Code Anmledung Seite in dem Standart Browser.
        /// </summary>
        public static string Azure_ActionBar_OpenDeviceCodePage_ToolTip {
            get {
                return ResourceManager.GetString("Azure_ActionBar_OpenDeviceCodePage_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startet den aktuellen Azure Prozess um die Daten auszuwerten.
        /// </summary>
        public static string Azure_ActionBar_Start_ToolTip {
            get {
                return ResourceManager.GetString("Azure_ActionBar_Start_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weitere Einstellungen.
        /// </summary>
        public static string Azure_ActionBar_ThreeDotsMenu_ToolTip {
            get {
                return ResourceManager.GetString("Azure_ActionBar_ThreeDotsMenu_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivität.
        /// </summary>
        public static string Azure_Activity_Placeholder {
            get {
                return ResourceManager.GetString("Azure_Activity_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Aktivitäten.
        /// </summary>
        public static string Azure_AuditActivity_Label {
            get {
                return ResourceManager.GetString("Azure_AuditActivity_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellt.
        /// </summary>
        public static string Azure_AuditCreated_Label {
            get {
                return ResourceManager.GetString("Azure_AuditCreated_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existierende Abfrage.
        /// </summary>
        public static string Azure_AuditQuery_Label {
            get {
                return ResourceManager.GetString("Azure_AuditQuery_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abfragen ID.
        /// </summary>
        public static string Azure_AuditQueryID_PlaceHolder {
            get {
                return ResourceManager.GetString("Azure_AuditQueryID_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Azure_AuditType_Label {
            get {
                return ResourceManager.GetString("Azure_AuditType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer.
        /// </summary>
        public static string Azure_AuditUPN_Label {
            get {
                return ResourceManager.GetString("Azure_AuditUPN_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguriere das End Datum wo die Suche enden soll.
        /// </summary>
        public static string Azure_DateFilter_Date_End_ToolTip {
            get {
                return ResourceManager.GetString("Azure_DateFilter_Date_End_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguriere das Start Datum wo die Suche starten soll.
        /// </summary>
        public static string Azure_DateFilter_Date_Start_ToolTip {
            get {
                return ResourceManager.GetString("Azure_DateFilter_Date_Start_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguriere die Uhrzeit bei welcher die Suche enden soll.
        /// </summary>
        public static string Azure_DateFilter_Time_End_ToolTip {
            get {
                return ResourceManager.GetString("Azure_DateFilter_Time_End_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguriere die Uhrzeit bei welcher die Suche starten soll.
        /// </summary>
        public static string Azure_DateFilter_Time_Start_ToolTip {
            get {
                return ResourceManager.GetString("Azure_DateFilter_Time_Start_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string Azure_DeleteItem_Label {
            get {
                return ResourceManager.GetString("Azure_DeleteItem_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es werden keine Items gelöscht.
        /// </summary>
        public static string Azure_DeleteItem_Off_Label {
            get {
                return ResourceManager.GetString("Azure_DeleteItem_Off_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items werden gelöscht.
        /// </summary>
        public static string Azure_DeleteItem_On_Label {
            get {
                return ResourceManager.GetString("Azure_DeleteItem_On_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten exportieren.
        /// </summary>
        public static string Azure_ExportData_Label {
            get {
                return ResourceManager.GetString("Azure_ExportData_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen eines weiteren Gruppen Filter (Entra Gruppen Guid).
        /// </summary>
        public static string Azure_GroupFilter_Button_Add_ToolTip {
            get {
                return ResourceManager.GetString("Azure_GroupFilter_Button_Add_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen des ausgewählten Gruppen Filter.
        /// </summary>
        public static string Azure_GroupFilter_Button_Remove_ToolTip {
            get {
                return ResourceManager.GetString("Azure_GroupFilter_Button_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppen Filter.
        /// </summary>
        public static string Azure_GroupFilter_Label {
            get {
                return ResourceManager.GetString("Azure_GroupFilter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppen ID.
        /// </summary>
        public static string Azure_GroupFilter_Placeholder {
            get {
                return ResourceManager.GetString("Azure_GroupFilter_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stunde.
        /// </summary>
        public static string Azure_Hour_Placeholder {
            get {
                return ResourceManager.GetString("Azure_Hour_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden der bereits exportieren MFA Daten.
        /// </summary>
        public static string Azure_LoadFile_Title {
            get {
                return ResourceManager.GetString("Azure_LoadFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anschauen Und Löschen.
        /// </summary>
        public static string Azure_Mail_Action_Delete_Text {
            get {
                return ResourceManager.GetString("Azure_Mail_Action_Delete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzeigen.
        /// </summary>
        public static string Azure_Mail_Action_Preview_Text {
            get {
                return ResourceManager.GetString("Azure_Mail_Action_Preview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail gelöscht.
        /// </summary>
        public static string Azure_Mail_Deleted_DataGridHeader {
            get {
                return ResourceManager.GetString("Azure_Mail_Deleted_DataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ursprungs-Mail.
        /// </summary>
        public static string Azure_Mail_From_DataGridHeader {
            get {
                return ResourceManager.GetString("Azure_Mail_From_DataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffne die aktuelle Mail im Browser.
        /// </summary>
        public static string Azure_Mail_OpenMail_ToolTip {
            get {
                return ResourceManager.GetString("Azure_Mail_OpenMail_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erhalten an.
        /// </summary>
        public static string Azure_Mail_Received_DataGridHeader {
            get {
                return ResourceManager.GetString("Azure_Mail_Received_DataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betreff.
        /// </summary>
        public static string Azure_Mail_Subject_DataGridHeader {
            get {
                return ResourceManager.GetString("Azure_Mail_Subject_DataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Azure_Minute_Placeholder {
            get {
                return ResourceManager.GetString("Azure_Minute_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser öffnen um den Code einzugeben.
        /// </summary>
        public static string Azure_OpenBrowser_ButtonToolTip {
            get {
                return ResourceManager.GetString("Azure_OpenBrowser_ButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgabetiefe.
        /// </summary>
        public static string Azure_ReportLevel_Main {
            get {
                return ResourceManager.GetString("Azure_ReportLevel_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Füge einen neuen Scope hinzu (Berechtigung welcher IRH.Ui verwenden soll).
        /// </summary>
        public static string Azure_Scope_Add_ToolTip {
            get {
                return ResourceManager.GetString("Azure_Scope_Add_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Berechtigungen.
        /// </summary>
        public static string Azure_Scope_Label {
            get {
                return ResourceManager.GetString("Azure_Scope_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechtigung.
        /// </summary>
        public static string Azure_Scope_Placeholder {
            get {
                return ResourceManager.GetString("Azure_Scope_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entferne den aktuellen Scope (Berechtigung).
        /// </summary>
        public static string Azure_Scope_Remove_ToolTip {
            get {
                return ResourceManager.GetString("Azure_Scope_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starten.
        /// </summary>
        public static string Azure_StartProcess_Label {
            get {
                return ResourceManager.GetString("Azure_StartProcess_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Füge eine Betreff Filter hinzu welcher verwendet wird um die Mails zu durchsuchen (Der Filter ist ein: Contains KEIN Equals).
        /// </summary>
        public static string Azure_SubjectFilter_Add_ToolTip {
            get {
                return ResourceManager.GetString("Azure_SubjectFilter_Add_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betreff Filter.
        /// </summary>
        public static string Azure_SubjectFilter_Label {
            get {
                return ResourceManager.GetString("Azure_SubjectFilter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betreff.
        /// </summary>
        public static string Azure_SubjectFilter_Placeholder {
            get {
                return ResourceManager.GetString("Azure_SubjectFilter_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entferne den aktuellen Betreff Filter.
        /// </summary>
        public static string Azure_SubjectFilter_Remove_ToolTip {
            get {
                return ResourceManager.GetString("Azure_SubjectFilter_Remove_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPrincipleName.
        /// </summary>
        public static string Azure_UPN_DataGridHeader {
            get {
                return ResourceManager.GetString("Azure_UPN_DataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum konfigurieren.
        /// </summary>
        public static string AzureLoginAudit_DateMenu_Label {
            get {
                return ResourceManager.GetString("AzureLoginAudit_DateMenu_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enddatum.
        /// </summary>
        public static string AzureLoginAudit_EndDate_Label {
            get {
                return ResourceManager.GetString("AzureLoginAudit_EndDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Datum.
        /// </summary>
        public static string AzureLoginAudit_StartDate_Label {
            get {
                return ResourceManager.GetString("AzureLoginAudit_StartDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA Anzahl.
        /// </summary>
        public static string AzureMFA_MFACount_DataGrid {
            get {
                return ResourceManager.GetString("AzureMFA_MFACount_DataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multifaktor.
        /// </summary>
        public static string AzureMFA_MFAHeader_Label {
            get {
                return ResourceManager.GetString("AzureMFA_MFAHeader_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methoden.
        /// </summary>
        public static string AzureMFA_MFAName_DataGrid {
            get {
                return ResourceManager.GetString("AzureMFA_MFAName_DataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern der Export Daten.
        /// </summary>
        public static string AzureMFA_SaveFile_Title {
            get {
                return ResourceManager.GetString("AzureMFA_SaveFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer Sitzungen zurückgesetzt.
        /// </summary>
        public static string AzureSession_ResetSession_DataGridHeader {
            get {
                return ResourceManager.GetString("AzureSession_ResetSession_DataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/generalsle1n/IRH/.
        /// </summary>
        public static string Common_GitHubUrl {
            get {
                return ResourceManager.GetString("Common_GitHubUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRH.Ui.
        /// </summary>
        public static string Common_ProgramName {
            get {
                return ResourceManager.GetString("Common_ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 0.1.
        /// </summary>
        public static string Common_Version {
            get {
                return ResourceManager.GetString("Common_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c0849608-c8b9-4e86-b37d-fce972a0a7f6.
        /// </summary>
        public static string Setting_AppID_Default {
            get {
                return ResourceManager.GetString("Setting_AppID_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern Sie die App-ID in eine benutzerdefinierte ID, in der Regel ist dies nicht erforderlich und die Standardeinstellung ist die richtige.
        /// </summary>
        public static string Setting_AppID_Description {
            get {
                return ResourceManager.GetString("Setting_AppID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendungs ID.
        /// </summary>
        public static string Setting_AppID_Main {
            get {
                return ResourceManager.GetString("Setting_AppID_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern sie die aktuelle Sprache.
        /// </summary>
        public static string Setting_AppLanguage_Description {
            get {
                return ResourceManager.GetString("Setting_AppLanguage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        public static string Setting_AppLanguage_Main {
            get {
                return ResourceManager.GetString("Setting_AppLanguage_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern des aktuellen Theme.
        /// </summary>
        public static string Setting_AppTheme_Description {
            get {
                return ResourceManager.GetString("Setting_AppTheme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Design.
        /// </summary>
        public static string Setting_AppTheme_Main {
            get {
                return ResourceManager.GetString("Setting_AppTheme_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern des zu verwendenden Authentifizierungs Type.
        /// </summary>
        public static string Setting_AuthType_Description {
            get {
                return ResourceManager.GetString("Setting_AuthType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentifizierung.
        /// </summary>
        public static string Setting_AuthType_Main {
            get {
                return ResourceManager.GetString("Setting_AuthType_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivieren sie die experimentellen Funktionen, welche noch nicht vollständig getestest sind, verwenden auf eigene Gefahr. Das ändern der Option fordert ein Neustart der anwendung.
        /// </summary>
        public static string Setting_Experimental_Description {
            get {
                return ResourceManager.GetString("Setting_Experimental_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimentelle Funktionen.
        /// </summary>
        public static string Setting_Experimental_Main {
            get {
                return ResourceManager.GetString("Setting_Experimental_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_AppID.
        /// </summary>
        public static string Setting_Name_AppID {
            get {
                return ResourceManager.GetString("Setting_Name_AppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_Name_AppIDEditEnabled.
        /// </summary>
        public static string Setting_Name_AppIDEditEnabled {
            get {
                return ResourceManager.GetString("Setting_Name_AppIDEditEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_Name_AppLanguage.
        /// </summary>
        public static string Setting_Name_AppLanguage {
            get {
                return ResourceManager.GetString("Setting_Name_AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_AppTheme.
        /// </summary>
        public static string Setting_Name_AppTheme {
            get {
                return ResourceManager.GetString("Setting_Name_AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_AuthType.
        /// </summary>
        public static string Setting_Name_AuthType {
            get {
                return ResourceManager.GetString("Setting_Name_AuthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_ExperimentalEnabled.
        /// </summary>
        public static string Setting_Name_ExperimentalEnabled {
            get {
                return ResourceManager.GetString("Setting_Name_ExperimentalEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_TenantID.
        /// </summary>
        public static string Setting_Name_TenantID {
            get {
                return ResourceManager.GetString("Setting_Name_TenantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_TenantIDEditEnabled.
        /// </summary>
        public static string Setting_Name_TenantIDEditEnabled {
            get {
                return ResourceManager.GetString("Setting_Name_TenantIDEditEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt Link.
        /// </summary>
        public static string Setting_ProjectUrl {
            get {
                return ResourceManager.GetString("Setting_ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösche alle Hintergrund Konfig.
        /// </summary>
        public static string Setting_Reset_Description {
            get {
                return ResourceManager.GetString("Setting_Reset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        public static string Setting_Reset_Main {
            get {
                return ResourceManager.GetString("Setting_Reset_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to common.
        /// </summary>
        public static string Setting_TenantID_Default {
            get {
                return ResourceManager.GetString("Setting_TenantID_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern Sie die Organistations ID, in der Regel ist dies nicht erforderlich und „common“ ist das richtige.
        /// </summary>
        public static string Setting_TenantID_Description {
            get {
                return ResourceManager.GetString("Setting_TenantID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organistations ID.
        /// </summary>
        public static string Setting_TenantID_Main {
            get {
                return ResourceManager.GetString("Setting_TenantID_Main", resourceCulture);
            }
        }
    }
}
