//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRH.Ui.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRH.Ui.Resources.Strings.de", typeof(Strings_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten exportieren.
        /// </summary>
        public static string Azure_ExportData_Label {
            get {
                return ResourceManager.GetString("Azure_ExportData_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppen Filter.
        /// </summary>
        public static string Azure_GroupFilter_Label {
            get {
                return ResourceManager.GetString("Azure_GroupFilter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppen ID.
        /// </summary>
        public static string Azure_GroupFilter_Placeholder {
            get {
                return ResourceManager.GetString("Azure_GroupFilter_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden der bereits exportieren MFA Daten.
        /// </summary>
        public static string Azure_LoadFile_Title {
            get {
                return ResourceManager.GetString("Azure_LoadFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser öffnen um den Code einzugeben.
        /// </summary>
        public static string Azure_OpenBrowser_ButtonToolTip {
            get {
                return ResourceManager.GetString("Azure_OpenBrowser_ButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgabetiefe.
        /// </summary>
        public static string Azure_ReportLevel_Main {
            get {
                return ResourceManager.GetString("Azure_ReportLevel_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Berechtigungen.
        /// </summary>
        public static string Azure_Scope_Label {
            get {
                return ResourceManager.GetString("Azure_Scope_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechtigung.
        /// </summary>
        public static string Azure_Scope_Placeholder {
            get {
                return ResourceManager.GetString("Azure_Scope_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starten.
        /// </summary>
        public static string Azure_StartProcess_Label {
            get {
                return ResourceManager.GetString("Azure_StartProcess_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPrincipleName.
        /// </summary>
        public static string Azure_UPN_DataGridHeader {
            get {
                return ResourceManager.GetString("Azure_UPN_DataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA Anzahl.
        /// </summary>
        public static string AzureMFA_MFACount_DataGrid {
            get {
                return ResourceManager.GetString("AzureMFA_MFACount_DataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methoden.
        /// </summary>
        public static string AzureMFA_MFAName_DataGrid {
            get {
                return ResourceManager.GetString("AzureMFA_MFAName_DataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern der Export Daten.
        /// </summary>
        public static string AzureMFA_SaveFile_Title {
            get {
                return ResourceManager.GetString("AzureMFA_SaveFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer Sitzungen zurückgesetzt.
        /// </summary>
        public static string AzureSession_ResetSession_DataGridHeader {
            get {
                return ResourceManager.GetString("AzureSession_ResetSession_DataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/generalsle1n/IRH/.
        /// </summary>
        public static string Common_GitHubUrl {
            get {
                return ResourceManager.GetString("Common_GitHubUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRH.Ui.
        /// </summary>
        public static string Common_ProgramName {
            get {
                return ResourceManager.GetString("Common_ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 0.1.
        /// </summary>
        public static string Common_Version {
            get {
                return ResourceManager.GetString("Common_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c0849608-c8b9-4e86-b37d-fce972a0a7f6.
        /// </summary>
        public static string Setting_AppID_Default {
            get {
                return ResourceManager.GetString("Setting_AppID_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern Sie die App-ID in eine benutzerdefinierte ID, in der Regel ist dies nicht erforderlich und die Standardeinstellung ist die richtige.
        /// </summary>
        public static string Setting_AppID_Description {
            get {
                return ResourceManager.GetString("Setting_AppID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anwendungs ID.
        /// </summary>
        public static string Setting_AppID_Main {
            get {
                return ResourceManager.GetString("Setting_AppID_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern des aktuellen Theme.
        /// </summary>
        public static string Setting_AppTheme_Description {
            get {
                return ResourceManager.GetString("Setting_AppTheme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Design.
        /// </summary>
        public static string Setting_AppTheme_Main {
            get {
                return ResourceManager.GetString("Setting_AppTheme_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern des zu verwendenden Authentifizierungs Type.
        /// </summary>
        public static string Setting_AuthType_Description {
            get {
                return ResourceManager.GetString("Setting_AuthType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentifizierung.
        /// </summary>
        public static string Setting_AuthType_Main {
            get {
                return ResourceManager.GetString("Setting_AuthType_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_AppID.
        /// </summary>
        public static string Setting_Name_AppID {
            get {
                return ResourceManager.GetString("Setting_Name_AppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_Name_AppIDEditEnabled.
        /// </summary>
        public static string Setting_Name_AppIDEditEnabled {
            get {
                return ResourceManager.GetString("Setting_Name_AppIDEditEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_AppTheme.
        /// </summary>
        public static string Setting_Name_AppTheme {
            get {
                return ResourceManager.GetString("Setting_Name_AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_AuthType.
        /// </summary>
        public static string Setting_Name_AuthType {
            get {
                return ResourceManager.GetString("Setting_Name_AuthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_TenantID.
        /// </summary>
        public static string Setting_Name_TenantID {
            get {
                return ResourceManager.GetString("Setting_Name_TenantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_TenantIDEditEnabled.
        /// </summary>
        public static string Setting_Name_TenantIDEditEnabled {
            get {
                return ResourceManager.GetString("Setting_Name_TenantIDEditEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt Link.
        /// </summary>
        public static string Setting_ProjectUrl {
            get {
                return ResourceManager.GetString("Setting_ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösche alle Hintergrund Konfig.
        /// </summary>
        public static string Setting_Reset_Description {
            get {
                return ResourceManager.GetString("Setting_Reset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurücksetzen.
        /// </summary>
        public static string Setting_Reset_Main {
            get {
                return ResourceManager.GetString("Setting_Reset_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to common.
        /// </summary>
        public static string Setting_TenantID_Default {
            get {
                return ResourceManager.GetString("Setting_TenantID_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändern Sie die Organistations ID, in der Regel ist dies nicht erforderlich und „common“ ist das richtige.
        /// </summary>
        public static string Setting_TenantID_Description {
            get {
                return ResourceManager.GetString("Setting_TenantID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organistations ID.
        /// </summary>
        public static string Setting_TenantID_Main {
            get {
                return ResourceManager.GetString("Setting_TenantID_Main", resourceCulture);
            }
        }
    }
}
