//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRH.Ui.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRH.Ui.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string Azure_Activity_Placeholder {
            get {
                return ResourceManager.GetString("Azure_Activity_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Activities.
        /// </summary>
        public static string Azure_AuditActivity_Label {
            get {
                return ResourceManager.GetString("Azure_AuditActivity_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Azure_AuditCreated_Label {
            get {
                return ResourceManager.GetString("Azure_AuditCreated_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Query.
        /// </summary>
        public static string Azure_AuditQuery_Label {
            get {
                return ResourceManager.GetString("Azure_AuditQuery_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query ID.
        /// </summary>
        public static string Azure_AuditQueryID_PlaceHolder {
            get {
                return ResourceManager.GetString("Azure_AuditQueryID_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Azure_AuditType_Label {
            get {
                return ResourceManager.GetString("Azure_AuditType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Azure_AuditUPN_Label {
            get {
                return ResourceManager.GetString("Azure_AuditUPN_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Azure_AuditUser_Label {
            get {
                return ResourceManager.GetString("Azure_AuditUser_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Data.
        /// </summary>
        public static string Azure_ExportData_Label {
            get {
                return ResourceManager.GetString("Azure_ExportData_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Filter.
        /// </summary>
        public static string Azure_GroupFilter_Label {
            get {
                return ResourceManager.GetString("Azure_GroupFilter_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group ID.
        /// </summary>
        public static string Azure_GroupFilter_Placeholder {
            get {
                return ResourceManager.GetString("Azure_GroupFilter_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Azure_Hour_Placeholder {
            get {
                return ResourceManager.GetString("Azure_Hour_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load existing MFA Data.
        /// </summary>
        public static string Azure_LoadFile_Title {
            get {
                return ResourceManager.GetString("Azure_LoadFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail deleted.
        /// </summary>
        public static string Azure_Mail_Deleted_DataGridHeader {
            get {
                return ResourceManager.GetString("Azure_Mail_Deleted_DataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Mail.
        /// </summary>
        public static string Azure_Mail_From_DataGridHeader {
            get {
                return ResourceManager.GetString("Azure_Mail_From_DataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Azure_Mail_Received_DataGridHeader {
            get {
                return ResourceManager.GetString("Azure_Mail_Received_DataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Azure_Mail_Subject_DataGridHeader {
            get {
                return ResourceManager.GetString("Azure_Mail_Subject_DataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Azure_Minute_Placeholder {
            get {
                return ResourceManager.GetString("Azure_Minute_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Browser to enter Code.
        /// </summary>
        public static string Azure_OpenBrowser_ButtonToolTip {
            get {
                return ResourceManager.GetString("Azure_OpenBrowser_ButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printlevel.
        /// </summary>
        public static string Azure_ReportLevel_Main {
            get {
                return ResourceManager.GetString("Azure_ReportLevel_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Permissions.
        /// </summary>
        public static string Azure_Scope_Label {
            get {
                return ResourceManager.GetString("Azure_Scope_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Azure_Scope_Placeholder {
            get {
                return ResourceManager.GetString("Azure_Scope_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Azure_StartProcess_Label {
            get {
                return ResourceManager.GetString("Azure_StartProcess_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPrincipleName.
        /// </summary>
        public static string Azure_UPN_DataGridHeader {
            get {
                return ResourceManager.GetString("Azure_UPN_DataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Dates.
        /// </summary>
        public static string AzureLoginAudit_DateMenu_Label {
            get {
                return ResourceManager.GetString("AzureLoginAudit_DateMenu_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string AzureLoginAudit_EndDate_Label {
            get {
                return ResourceManager.GetString("AzureLoginAudit_EndDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string AzureLoginAudit_StartDate_Label {
            get {
                return ResourceManager.GetString("AzureLoginAudit_StartDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA Count.
        /// </summary>
        public static string AzureMFA_MFACount_DataGrid {
            get {
                return ResourceManager.GetString("AzureMFA_MFACount_DataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multifactor.
        /// </summary>
        public static string AzureMFA_MFAHeader_Label {
            get {
                return ResourceManager.GetString("AzureMFA_MFAHeader_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods.
        /// </summary>
        public static string AzureMFA_MFAName_DataGrid {
            get {
                return ResourceManager.GetString("AzureMFA_MFAName_DataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save MFA Data.
        /// </summary>
        public static string AzureMFA_SaveFile_Title {
            get {
                return ResourceManager.GetString("AzureMFA_SaveFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Session revoked.
        /// </summary>
        public static string AzureSession_ResetSession_DataGridHeader {
            get {
                return ResourceManager.GetString("AzureSession_ResetSession_DataGridHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/generalsle1n/IRH/.
        /// </summary>
        public static string Common_GitHubUrl {
            get {
                return ResourceManager.GetString("Common_GitHubUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRH.Ui.
        /// </summary>
        public static string Common_ProgramName {
            get {
                return ResourceManager.GetString("Common_ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 0.1.
        /// </summary>
        public static string Common_Version {
            get {
                return ResourceManager.GetString("Common_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c0849608-c8b9-4e86-b37d-fce972a0a7f6.
        /// </summary>
        public static string Setting_AppID_Default {
            get {
                return ResourceManager.GetString("Setting_AppID_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the App ID to an custom ID, usally this is dont required and default is the right.
        /// </summary>
        public static string Setting_AppID_Description {
            get {
                return ResourceManager.GetString("Setting_AppID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App ID.
        /// </summary>
        public static string Setting_AppID_Main {
            get {
                return ResourceManager.GetString("Setting_AppID_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the current app theme.
        /// </summary>
        public static string Setting_AppTheme_Description {
            get {
                return ResourceManager.GetString("Setting_AppTheme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Theme.
        /// </summary>
        public static string Setting_AppTheme_Main {
            get {
                return ResourceManager.GetString("Setting_AppTheme_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the used authentication Type.
        /// </summary>
        public static string Setting_AuthType_Description {
            get {
                return ResourceManager.GetString("Setting_AuthType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Setting_AuthType_Main {
            get {
                return ResourceManager.GetString("Setting_AuthType_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_AppID.
        /// </summary>
        public static string Setting_Name_AppID {
            get {
                return ResourceManager.GetString("Setting_Name_AppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_Name_AppIDEditEnabled.
        /// </summary>
        public static string Setting_Name_AppIDEditEnabled {
            get {
                return ResourceManager.GetString("Setting_Name_AppIDEditEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_AppTheme.
        /// </summary>
        public static string Setting_Name_AppTheme {
            get {
                return ResourceManager.GetString("Setting_Name_AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_AuthType.
        /// </summary>
        public static string Setting_Name_AuthType {
            get {
                return ResourceManager.GetString("Setting_Name_AuthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_TenantID.
        /// </summary>
        public static string Setting_Name_TenantID {
            get {
                return ResourceManager.GetString("Setting_Name_TenantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting_TenantIDEditEnabled.
        /// </summary>
        public static string Setting_Name_TenantIDEditEnabled {
            get {
                return ResourceManager.GetString("Setting_Name_TenantIDEditEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Url.
        /// </summary>
        public static string Setting_ProjectUrl {
            get {
                return ResourceManager.GetString("Setting_ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all stored Backend Config.
        /// </summary>
        public static string Setting_Reset_Description {
            get {
                return ResourceManager.GetString("Setting_Reset_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Setting_Reset_Main {
            get {
                return ResourceManager.GetString("Setting_Reset_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to common.
        /// </summary>
        public static string Setting_TenantID_Default {
            get {
                return ResourceManager.GetString("Setting_TenantID_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the Tenant ID, usally this is dont required and &quot;common&quot; is the right.
        /// </summary>
        public static string Setting_TenantID_Description {
            get {
                return ResourceManager.GetString("Setting_TenantID_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant ID.
        /// </summary>
        public static string Setting_TenantID_Main {
            get {
                return ResourceManager.GetString("Setting_TenantID_Main", resourceCulture);
            }
        }
    }
}
