on:
  workflow_call:
    inputs:
      nextReleaseMode:
        required: true
        type: string
    outputs:
      nextVersion: 
        value: ${{ jobs.IncreaseRelease.outputs.next-version }}
        
jobs:
  computeNextRelease:
    runs-on: self-hosted
    steps:
      #Get Version from Release  
      - name: GetVersion
        id: GetVersion
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}

      #Increase Version from Release
      - name: IncreaseRelease
        id: IncreaseRelease
        uses: christian-draeger/increment-semantic-version@1.2.3
        with:
          current-version: ${{ steps.GetVersion.outputs.release }}
          version-fragment: ${{ inputs.nextReleaseMode }}
        
      
