name: Create Release
on:
  workflow_call:
    inputs:
      nextVersion:
        type: string
        required: true
jobs:
  createRelease:
    name: Create Release
    
    permissions: 
      contents: write
    
    runs-on: self-hosted
    
    steps:
      - name: DownloadArtifact
        uses: actions/download-artifact@v7

      - name: CreateRelease
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.nextVersion }}
          generate_release_notes: true
          make_latest: true
          files: "*"
    
        
