name: "Build Release and Push to Release"
on:
  push:
    branches: 
      - "master"
      - "Issue#62"

jobs:
  build_win-x64:
    runs-on: "windows-latest" 
    steps:
      - uses: actions/checkout@v6.0.1
