name: "Build Release and Push to Release"

env:
  CurrentDotnetVersion: 9
  InstallVPKCommand: "dotnet tool install -g vpk"
  PublishIRHCLI: "dotnet publish IRH\\IRH.csproj"
  PublishIRHCLIReleaseFolder: "IRH\\IRH\\bin\\Release\\net9.0\\publish\\"
  DefaultNextReleaseMode: "patch"
  
on:
  push:
    branches: 
      - "master"
      - "Issue#62"

jobs:
  build_win-x64:
    runs-on: "windows-latest" 
    steps:
      #Clone Repository
      #- uses: actions/checkout@v6.0.1
      #  with:
      #    lfs: true
          
      #Install .Net with Version 9.X
      #- name: CreateDotNetEnvironment
      #  uses: actions/setup-dotnet@v5
      #  with: 
      #    dotnet-version: ${{ env.CurrentDotnetVersion }}
          
      #- name: BuildIRH
      #  run: ${{ env.PublishIRHCLI }}
      #- name: InstallVeloPack
      #  run: ${{ env.InstallVPKCommand }}
        
      - name: GetVersion
        id: GetVersion
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
          
      - name: IncreaseRelease
        id: IncreaseRelease
        uses: christian-draeger/increment-semantic-version@1.2.3
        with:
          current-version: ${{ steps.GetVersion.outputs.release }}
          version-fragment: ${{ env.DefaultNextReleaseMode }}
          
      - name: CreateVeloPackRelease
        run: "vpk pack --packId IRH --packVersion ${{ steps.IncreaseRelease.outputs.next-version }} --packDir ${{ env.PublishIRHCLIReleaseFolder }}"
